FRONTEND_IMAGE_NAME='frontend'

.PHONY: node_modules
node_modules:
	npm install

.PHONY: dev
dev: node_modules
	npm run dev

.PHONY: test
test: node_modules
	npm run test

.PHONY: build
build: node_modules
	npm run build

